const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    info: {
      title: 'Todo Map API',
      version: '1.0.0',
      description: 'Todo Map API with autogenerated swagger doc'
    },
    basePath: '/',
    "schemes": [
      "http"
    ],
    definitions: {
      User: {
        type: "object",
        properties: {
          username: {
            type: "string"
          },
          password: {
            "type": "string"
          },
          firstName: {
            type: "string"
          }
        },
      }
    }
  },
  apis: ['./controllers/*']
};

const specs = swaggerJsdoc(options);

module.exports = app => {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
};
